# Generated by Django 4.0.2 on 2022-02-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
