# Generated by Django 4.0.2 on 2022-02-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_codes', '0002_alter_chatcode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('group_type', models.CharField(choices=[('discord', 'Discord'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=255)),
                ('show_name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('sem_tri', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_codes.chatcode')),
            ],
        ),
    ]
