# Generated by Django 4.0.2 on 2022-02-14 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sem_tri',
        ),
    ]
