# Generated by Django 4.0.2 on 2022-02-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_sem_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='group_link',
            field=models.CharField(default='no_link', max_length=255),
            preserve_default=False,
        ),
    ]
